name: Digital Ocean CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Client and Server
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Stop Services
        run: |
            pm2 stop 0
            pm2 stop 1
            pm2 save
            sudo service nginx stop
      - name: Npm install Server
        run: |
            cd server
            npm ci
      - name: Npm install Client
        run: |
            cd client
            npm ci
      - name: Build Client
        run: |
            cd client
            npm run build
      - name: Start Services
        run: |
            pm2 start 0
            pm2 start 1
            pm2 save
            sudo service nginx start