name: Digital Ocean CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Server
        run: |
            ls -ltr
            cd server
            npm ci
            pm2 stop 0
            pm2 start 0
            pm2 save
      - name: Setup Client
        run: |
            ls -ltr
            cd client
            npm ci
            npm run build
            pm2 stop 1
            pm2 start 1
            pm2 save
            sudo service nginx restart